networks:
  mlops-network:
    external: true

services:
  vault:
    image: hashicorp/vault:1.17
    container_name: vault_1.17
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http:/127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/file:/vault/file:rw
      - ./vault/config:/vault/config:rw
    restart: always
    entrypoint: vault server -config=/vault/config/config.json
    networks:
      mlops-network:
        ipv4_address: 172.61.0.15
